FROM ruby:2.5.3

RUN apt-get clean && apt-get update && apt-get install -y libpq-dev libxml2-dev libxslt-dev mysql-client

WORKDIR /app
COPY . /app

RUN gem install bundler && bundle install --jobs 20 --retry 5

CMD ["rails", "server", "-b", "0.0.0.0", "-p", "4000"]
