export const INITIAL_USER_LOAD_SUCCESS = 'INITIAL_USER_LOAD_SUCCESS';
export const INITIAL_USER_LOAD_FAILURE = 'INITIAL_USER_LOAD_FAILURE';

// authentication
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';

// resumes
export const REQUEST_RESUMES_SUCCESS = 'REQUEST_RESUMES_SUCCESS';
export const REQUEST_RESUMES_FAILURE = 'REQUEST_RESUMES_FAILURE';
